--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/zFrozead0s/ZF-Reports
build-by-default: true
branches:
- main
projects:
  ZF-Reports:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
